// Mock database for the prototype. Mirrors the planned platform entities so a
// later slice can swap this for API calls. seedData() must return a FRESH object
// every call (the UI mutates it; refresh resets).
export function seedData() {
  return {
    users: [
      { id: 'u-exec', name: 'A. Reeves', role: 'executive' },
      { id: 'u-mgr', name: 'J. Blake', role: 'manager', managedArtistIds: ['a1', 'a2'] },
      { id: 'u-admin', name: 'Platform Admin', role: 'super_admin' },
    ],
    artists: [
      { id: 'a1', name: 'Nova Reign', genre: 'R&B', executiveId: 'u-exec' },
      { id: 'a2', name: 'Rico Vale', genre: 'Hip-Hop', executiveId: 'u-exec' },
      { id: 'a3', name: 'The Marlowes', genre: 'Alt Soul', executiveId: 'u-exec' },
      { id: 'a4', name: 'DJ Cassius', genre: 'Electronic', executiveId: 'u-other' },
    ],
    songs: [
      { id: 's1', artistId: 'a1', title: 'First Light', isrc: 'US-ECC-26-00001',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: false, splitSheetOnFile: true, advanceTradedEquity: false,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'Nova Reign', role: 'artist', pct: 60, approved: true },
          { name: 'Beat Chemist', role: 'producer', pct: 25, approved: true },
          { name: 'J. Pen', role: 'writer', pct: 15, approved: true },
        ] },
      { id: 's2', artistId: 'a1', title: 'Undertow', isrc: 'US-ECC-26-00002',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: true, splitSheetOnFile: true, advanceTradedEquity: false,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'Nova Reign', role: 'artist', pct: 70, approved: true },
          { name: 'Beat Chemist', role: 'producer', pct: 30, approved: true },
        ] },
      { id: 's3', artistId: 'a2', title: 'Night Drive', isrc: 'US-ECC-26-00003',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: true, splitSheetOnFile: false, advanceTradedEquity: false,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: false },
        splits: [
          { name: 'Rico Vale', role: 'artist', pct: 50, approved: true },
          { name: 'Track Marshal', role: 'producer', pct: 30, approved: true },
          { name: 'Lil Verse', role: 'writer', pct: 12, approved: false },
        ] },
      { id: 's4', artistId: 'a2', title: 'Fast Money', isrc: 'US-ECC-25-00090',
        masterOwner: 'label', publishingOwner: 'third_party',
        producerAgreementOnFile: true, splitSheetOnFile: true, advanceTradedEquity: true,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'Rico Vale', role: 'artist', pct: 40, approved: true },
          { name: 'D. Weaver', role: 'producer', pct: 40, approved: true },
          { name: 'Ghost Ink', role: 'writer', pct: 20, approved: true },
        ] },
      { id: 's5', artistId: 'a3', title: 'Midnight', isrc: '',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: true, splitSheetOnFile: true, advanceTradedEquity: false,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'The Marlowes', role: 'artist', pct: 80, approved: true },
          { name: 'Night Owl', role: 'producer', pct: 20, approved: true },
        ] },
      { id: 's6', artistId: 'a3', title: 'Second Wind', isrc: 'US-ECC-26-00006',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: true, splitSheetOnFile: true, advanceTradedEquity: false,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'The Marlowes', role: 'artist', pct: 75, approved: true },
          { name: 'Night Owl', role: 'producer', pct: 25, approved: true },
        ] },
      { id: 's7', artistId: 'a1', title: 'Horizon', isrc: 'US-ECC-26-00007',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: true, splitSheetOnFile: true, advanceTradedEquity: false,
        assets: { wavMaster: false, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'Nova Reign', role: 'artist', pct: 65, approved: true },
          { name: 'Beat Chemist', role: 'producer', pct: 35, approved: true },
        ] },
      { id: 's8', artistId: 'a4', title: 'Full Circle', isrc: 'US-ECC-25-00042',
        masterOwner: 'artist', publishingOwner: 'artist',
        producerAgreementOnFile: true, splitSheetOnFile: true, advanceTradedEquity: false,
        assets: { wavMaster: true, mp3Preview: true, artwork: true, lyricFile: true },
        splits: [
          { name: 'DJ Cassius', role: 'artist', pct: 100, approved: true },
        ] },
    ],
    releases: [
      { id: 'r1', title: 'First Light — Single', type: 'single', artistId: 'a1',
        status: 'executive_review', releaseDate: '2026-08-14', territories: ['Worldwide'],
        upc: '00602445001', songIds: ['s1'] },
      { id: 'r2', title: 'Night Drive — Single', type: 'single', artistId: 'a2',
        status: 'executive_review', releaseDate: '2026-08-01', territories: ['US', 'CA'],
        upc: '00602445002', songIds: ['s3'] },
      { id: 'r3', title: 'Midnight EP', type: 'ep', artistId: 'a3',
        status: 'executive_review', releaseDate: '2026-09-05', territories: ['Worldwide'],
        upc: '', songIds: ['s5', 's6'] },
      { id: 'r4', title: 'Undertow', type: 'single', artistId: 'a1',
        status: 'live', releaseDate: '2026-03-20', territories: ['Worldwide'],
        upc: '00602445004', songIds: ['s2'] },
      { id: 'r5', title: 'Fast Money', type: 'single', artistId: 'a2',
        status: 'live', releaseDate: '2025-11-07', territories: ['Worldwide'],
        upc: '00602445005', songIds: ['s4'] },
      { id: 'r6', title: 'Horizon', type: 'single', artistId: 'a1',
        status: 'asset_review', releaseDate: '2026-10-02', territories: ['Worldwide'],
        upc: '00602445006', songIds: ['s7'] },
      { id: 'r7', title: 'Full Circle LP', type: 'album', artistId: 'a4',
        status: 'scheduled', releaseDate: '2026-07-24', territories: ['Worldwide'],
        upc: '00602445007', songIds: ['s8'] },
    ],
    metrics: [
      { releaseId: 'r4', reportedStreams: 2400000, uniqueListeners: 610000,
        physicalSales: 8200, repeatPurchases: 1900, shippedUnits: 10000,
        verifiedSales: 9400, saves: 88000, playlistAdds: 12400, revenue: 41200 },
      { releaseId: 'r5', reportedStreams: 5100000, uniqueListeners: 890000,
        physicalSales: 320, repeatPurchases: 40, shippedUnits: 50000,
        verifiedSales: 61000, saves: 30100, playlistAdds: 9800, revenue: 18300 },
      { releaseId: 'r7', reportedStreams: 950000, uniqueListeners: 240000,
        physicalSales: 150, repeatPurchases: 12, shippedUnits: 20000,
        verifiedSales: 4100, saves: 8000, playlistAdds: 2100, revenue: 6900 },
    ],
    airplaySpins: [
      { songId: 's2', station: 'WQHT', market: 'New York', country: 'US', playedAt: '2026-07-06',
        sourceType: 'radio', detectionMethod: 'fingerprint', estAudience: 412000, confidence: 0.96 },
      { songId: 's2', station: 'KPWR', market: 'Los Angeles', country: 'US', playedAt: '2026-07-05',
        sourceType: 'radio', detectionMethod: 'fingerprint', estAudience: 380000, confidence: 0.94 },
      { songId: 's2', station: 'WGCI', market: 'Chicago', country: 'US', playedAt: '2026-07-05',
        sourceType: 'radio', detectionMethod: 'provider import', estAudience: 265000, confidence: 0.88 },
      { songId: 's4', station: 'WVEE', market: 'Atlanta', country: 'US', playedAt: '2026-07-04',
        sourceType: 'radio', detectionMethod: 'manual verification', estAudience: 240000, confidence: 0.75 },
      { songId: 's4', station: 'Shade 45', market: 'National', country: 'US', playedAt: '2026-07-03',
        sourceType: 'internet radio', detectionMethod: 'provider import', estAudience: 150000, confidence: 0.82 },
      { songId: 's2', station: 'WQHT', market: 'New York', country: 'US', playedAt: '2026-07-02',
        sourceType: 'radio', detectionMethod: 'fingerprint', estAudience: 405000, confidence: 0.97 },
      { songId: 's4', station: 'DJ Pool One', market: 'Southeast', country: 'US', playedAt: '2026-07-01',
        sourceType: 'DJ pool', detectionMethod: 'manual verification', estAudience: 60000, confidence: 0.6 },
      { songId: 's2', station: 'KBXX', market: 'Houston', country: 'US', playedAt: '2026-06-30',
        sourceType: 'radio', detectionMethod: 'fingerprint', estAudience: 210000, confidence: 0.93 },
    ],
    trend: [
      { label: 'Nov', value: 410000 }, { label: 'Dec', value: 520000 },
      { label: 'Jan', value: 480000 }, { label: 'Feb', value: 640000 },
      { label: 'Mar', value: 720000 }, { label: 'Apr', value: 690000 },
      { label: 'May', value: 810000 }, { label: 'Jun', value: 935000 },
    ],
    auditLog: [],
  };
}
